/** Public tuning contract for the sole Blob runtime (V2). */
export const BlobConfig = {
  v2: {
    initialBiomass: 192,
    maximumBiomass: 250,
    particleRadius: 0.16,
    maxFragments: 6,
    fixedStep: 1 / 30,
    maxSubsteps: 2,
    gravity: 18,
    cohesionThreshold: 36,
    cohesionDecayPerSecond: 12,
    cohesionDecayDelay: 0.75,
    fragmentReturnSeconds: 10,
    fragmentWitherSeconds: 1.5,
    fragmentReattachSeconds: 0.6,
    fragmentReturnSpeed: 2.3,
    fragmentReattachDistance: 0.45,
    redistributionDelaySeconds: 3,
    redistributionSeconds: 2,
    climb: {
      normalStep: 0.32,
      maximumHeight: 1.25,
      speed: 2.4,
    },
    flow: {
      brainCrossFraction: 0.6,
      speed: 2.9,
    },
    consumeSeconds: 1.5,
    coreHealth: 150,
    coreRadius: 0.35,
    coreDamageMultiplier: 2.5,
    propPushMaxDeltaV: 14,
    poseStrength: 12,
    contact: {
      damage: 6,
      interval: 0.35,
      baseRange: 1.7,
      attackSoundInterval: 1,
    },
  },
} as const;
