import { Euler, Vector3 } from "three";
import type {
  WeaponCategory,
  WeaponDefinition,
  WeaponId,
} from "@game/gameplay/weapons/core/WeaponDefinition";

/**
 * Mapa categorÃ­a â†’ nÃºmero de slot HL-style. Varias armas con la misma
 * categorÃ­a comparten slot (la tecla del slot cicla entre ellas en
 * `WeaponInventory.equipSlot`).
 */
export const SlotByCategory: Record<WeaponCategory, number> = {
  melee: 1,
  special: 1,
  sidearm: 2,
  automatic: 3,
  heavy: 4,
  throwable: 5,
};

/** CuÃ¡ntos slots hay en total. Usado por `WeaponController` para iterar las teclas. */
export const WEAPON_SLOT_COUNT = 5;

/**
 * ConfiguraciÃ³n data-driven de todas las armas del juego.
 *
 * Agregar un arma nueva = aÃ±adir una entrada acÃ¡ + (si su comportamiento no
 * encaja en hitscan/melee/special) crear una subclase de `Weapon`.
 * El factory en `WeaponFactory.createWeapon` la instancia segÃºn `type`.
 *
 * El orden de declaraciÃ³n define el orden de cycling dentro de un slot â€”
 * `smg` antes que `ar3` â‡’ presionar `3` con ambas equipadas alterna en ese
 * orden.
 *
 * Los `damage` son un port fiel del skill.cfg de HL2 (pistol 5, smg 4, ar2 8,
 * escopeta 8/perdigon, .357 40, rpg 100, granada 150, crowbar 10). Se ven bajos
 * a proposito: estan calibrados contra la vida de enemigos tambien portada de
 * HL2 (combine 50, zombie 50, headcrab 10). No subir sin reajustar ambas tablas.
 */
export const WeaponDefinitions: Record<WeaponId, WeaponDefinition> = {
  crowbar: {
    id: "crowbar",
    displayName: "Crowbar",
    modelId: "crowbar",
    pickupModelId: "crowbar",
    category: "melee",
    type: "melee",
    handedness: "oneHanded",
    damage: 10,
    fireRate: 2.2,
    magazineSize: 0,
    reserveAmmoMax: 0,
    ammoPerPickup: 0,
    spread: 0,
    range: 1.8,
    impulse: 5,
    reloadTime: 0,
    recoil: { vertical: 0.05, horizontal: 0.02, recovery: 10 },
    fireMode: "semi",
    reloadAnimationPitch: 0.32,
    muzzleFlash: {
      color: 0xffb24a,
      intensity: 0.8,
      duration: 0.06,
      size: 0.08,
    },
    canReceiveAmmoFromDuplicatePickup: false,
    hasAmmo: false,
    viewModelOffset: new Vector3(0.36, -0.24, -0.34),
    viewModelRotation: new Euler(-0.22, -0.295, -0.07),
    viewModelScale: 0.22,
    pickupScale: 0.525,
    pickupCollider: new Vector3(0.28, 1.02, 0.16),
    attackAnimationDuration: 0.32,
    attackAnimationPitch: 0.85,
    attackAnimationForward: 0.22,
  },
  pistol: {
    id: "pistol",
    displayName: "9mm Pistol",
    modelId: "pistol",
    pickupModelId: "pistol",
    category: "sidearm",
    type: "hitscan",
    handedness: "oneHanded",
    damage: 5,
    fireRate: 4,
    magazineSize: 18,
    reserveAmmoMax: 90,
    ammoPerPickup: 18,
    spread: 0.01,
    range: 85,
    impulse: 6,
    reloadTime: 1.05,
    recoil: { vertical: 0.06, horizontal: 0.025, recovery: 12 },
    fireMode: "semi",
    reloadAnimationPitch: 0.38,
    muzzleFlash: {
      color: 0xffb24a,
      intensity: 1.4,
      duration: 0.055,
      size: 0.11,
    },
    canReceiveAmmoFromDuplicatePickup: true,
    hasAmmo: true,
    viewModelOffset: new Vector3(0.29, -0.225, -0.4),
    viewModelRotation: new Euler(0.015, -0.18, 0.045),
    viewModelScale: 0.19,
    pickupScale: 0.18,
    pickupCollider: new Vector3(0.4, 0.24, 0.18),
  },
  revolver: {
    id: "revolver",
    displayName: ".357 Magnum",
    modelId: "revolver",
    pickupModelId: "revolver",
    category: "sidearm",
    type: "hitscan",
    handedness: "oneHanded",
    damage: 40,
    fireRate: 1.5,
    magazineSize: 6,
    reserveAmmoMax: 12,
    ammoPerPickup: 6,
    spread: 0.004,
    range: 100,
    impulse: 10,
    reloadTime: 1.5,
    recoil: { vertical: 0.14, horizontal: 0.03, recovery: 9 },
    fireMode: "semi",
    reloadAnimationPitch: 0.42,
    muzzleFlash: {
      color: 0xffc060,
      intensity: 2,
      duration: 0.07,
      size: 0.16,
    },
    canReceiveAmmoFromDuplicatePickup: true,
    hasAmmo: true,
    viewModelOffset: new Vector3(0.32, -0.235, -0.43),
    viewModelRotation: new Euler(0.022, -0.19, 0.045),
    viewModelScale: 0.27,
    pickupScale: 0.22,
    pickupCollider: new Vector3(0.46, 0.24, 0.18),
  },
  smg: {
    id: "smg",
    displayName: "SMG",
    modelId: "smg",
    pickupModelId: "smg",
    category: "automatic",
    type: "hitscan",
    handedness: "twoHanded",
    damage: 4,
    fireRate: 12,
    magazineSize: 45,
    reserveAmmoMax: 225,
    ammoPerPickup: 45,
    spread: 0.035,
    range: 70,
    impulse: 4,
    reloadTime: 1.35,
    recoil: { vertical: 0.035, horizontal: 0.035, recovery: 14 },
    fireMode: "auto",
    reloadAnimationPitch: 0.44,
    muzzleFlash: { color: 0xff9a2d, intensity: 1.2, duration: 0.04, size: 0.1 },
    canReceiveAmmoFromDuplicatePickup: true,
    hasAmmo: true,
    viewModelOffset: new Vector3(0.225, -0.18, -0.345),
    viewModelRotation: new Euler(-0.005, -0.105, 0.02),
    viewModelScale: 0.225,
    pickupScale: 0.315,
    pickupCollider: new Vector3(0.64, 0.24, 0.18),
    alternateFire: {
      kind: "grenadeLauncher",
      launchSpeed: 28,
      launchLift: 4,
    },
  },
  ar3: {
    id: "ar3",
    displayName: "AR3",
    modelId: "ar3",
    pickupModelId: "ar3",
    category: "automatic",
    type: "hitscan",
    handedness: "twoHanded",
    damage: 8,
    fireRate: 8,
    magazineSize: 30,
    reserveAmmoMax: 180,
    ammoPerPickup: 30,
    spread: 0.018,
    range: 100,
    impulse: 5,
    reloadTime: 1.45,
    recoil: { vertical: 0.045, horizontal: 0.025, recovery: 13 },
    fireMode: "auto",
    reloadAnimationPitch: 0.46,
    muzzleFlash: {
      color: 0xffb24a,
      intensity: 1.25,
      duration: 0.045,
      size: 0.11,
    },
    canReceiveAmmoFromDuplicatePickup: true,
    hasAmmo: true,
    viewModelOffset: new Vector3(0.22, -0.16, -0.315),
    viewModelRotation: new Euler(0.01, -0.12, 0.015),
    viewModelScale: 0.255,
    pickupScale: 0.43,
    pickupCollider: new Vector3(0.86, 0.36, 0.36),
    alternateFire: {
      kind: "energyBall",
      launchSpeed: 45,
    },
  },
  crossbow: {
    id: "crossbow",
    displayName: "Crossbow",
    modelId: "crossbow",
    pickupModelId: "crossbow",
    category: "automatic",
    type: "crossbow",
    handedness: "twoHanded",
    damage: 100,
    fireRate: 1,
    magazineSize: 1,
    reserveAmmoMax: 9,
    ammoPerPickup: 3,
    spread: 0,
    range: 120,
    impulse: 12,
    reloadTime: 1.2,
    recoil: { vertical: 0.09, horizontal: 0.02, recovery: 10 },
    fireMode: "semi",
    reloadAnimationPitch: 0.5,
    muzzleFlash: {
      color: 0x9fd4ff,
      intensity: 0.6,
      duration: 0.05,
      size: 0.08,
    },
    canReceiveAmmoFromDuplicatePickup: true,
    hasAmmo: true,
    viewModelOffset: new Vector3(0.255, -0.17, -0.335),
    viewModelRotation: new Euler(0.0, -0.145, -0.025),
    viewModelScale: 0.255,
    pickupScale: 0.47,
    pickupCollider: new Vector3(0.95, 0.34, 0.72),
  },
  shotgun: {
    id: "shotgun",
    displayName: "Shotgun",
    modelId: "shotgun",
    pickupModelId: "shotgun",
    category: "heavy",
    type: "shotgun",
    handedness: "twoHanded",
    damage: 8,
    fireRate: 1.1,
    magazineSize: 6,
    reserveAmmoMax: 24,
    ammoPerPickup: 6,
    spread: 0.08,
    range: 35,
    impulse: 7,
    reloadTime: 0.5,
    recoil: { vertical: 0.11, horizontal: 0.04, recovery: 11 },
    fireMode: "semi",
    reloadAnimationPitch: 0.48,
    muzzleFlash: {
      color: 0xffb24a,
      intensity: 1.8,
      duration: 0.07,
      size: 0.18,
    },
    canReceiveAmmoFromDuplicatePickup: true,
    hasAmmo: true,
    viewModelOffset: new Vector3(0.24, -0.18, -0.285),
    viewModelRotation: new Euler(-0.02, -0.1, 0.015),
    viewModelScale: 0.275,
    pickupScale: 0.47,
    pickupCollider: new Vector3(0.92, 0.26, 0.18),
    pelletsPerShot: 8,
    alternateFire: {
      kind: "doubleShot",
      damageMultiplier: 1.15,
      shotSpacing: 0.09,
      shellCost: 2,
    },
  },
  rpg: {
    id: "rpg",
    displayName: "RPG",
    modelId: "rpg",
    pickupModelId: "rpg",
    category: "heavy",
    type: "rpg",
    handedness: "twoHanded",
    damage: 100,
    fireRate: 2,
    magazineSize: 1,
    reserveAmmoMax: 2,
    ammoPerPickup: 1,
    spread: 0,
    range: 5.1,
    impulse: 26,
    reloadTime: 1.6,
    recoil: { vertical: 0.16, horizontal: 0.035, recovery: 8 },
    fireMode: "semi",
    reloadAnimationPitch: 0.58,
    muzzleFlash: {
      color: 0xffc07a,
      intensity: 2.2,
      duration: 0.11,
      size: 0.22,
    },
    canReceiveAmmoFromDuplicatePickup: true,
    hasAmmo: true,
    viewModelOffset: new Vector3(0.28, -0.205, -0.35),
    viewModelRotation: new Euler(0.0, -0.11, 0.03),
    viewModelScale: 0.285,
    pickupScale: 0.5,
    pickupCollider: new Vector3(1.0, 0.36, 0.3),
  },
  grenade: {
    id: "grenade",
    displayName: "Grenade",
    modelId: "grenade",
    pickupModelId: "grenade",
    category: "throwable",
    type: "grenade",
    handedness: "oneHanded",
    damage: 150,
    fireRate: 1.4,
    magazineSize: 0,
    reserveAmmoMax: 5,
    ammoPerPickup: 1,
    spread: 0,
    range: 4.5,
    impulse: 18,
    reloadTime: 0,
    recoil: { vertical: 0.04, horizontal: 0.01, recovery: 9 },
    fireMode: "semi",
    reloadAnimationPitch: 0.32,
    muzzleFlash: { color: 0x000000, intensity: 0, duration: 0, size: 0 },
    canReceiveAmmoFromDuplicatePickup: true,
    hasAmmo: true,
    viewModelOffset: new Vector3(0.36, -0.24, -0.37),
    viewModelRotation: new Euler(0.25, -0.205, 0.07),
    viewModelScale: 0.075,
    pickupScale: 0.085,
    pickupCollider: new Vector3(0.2, 0.2, 0.2),
    alternateFire: {
      kind: "closeThrow",
      throwSpeed: 11,
      throwLift: 5,
    },
  },
  gravityGun: {
    id: "gravityGun",
    displayName: "Gravity Gun",
    modelId: "gravityGun",
    pickupModelId: "gravityGun",
    category: "special",
    type: "special",
    handedness: "twoHanded",
    damage: 0,
    fireRate: 1.5,
    magazineSize: 0,
    reserveAmmoMax: 0,
    ammoPerPickup: 0,
    spread: 0,
    range: 0,
    impulse: 0,
    reloadTime: 0,
    recoil: { vertical: 0.025, horizontal: 0.01, recovery: 9 },
    fireMode: "semi",
    reloadAnimationPitch: 0.35,
    muzzleFlash: {
      color: 0x73dfff,
      intensity: 0.8,
      duration: 0.08,
      size: 0.14,
    },
    canReceiveAmmoFromDuplicatePickup: false,
    hasAmmo: false,
    viewModelOffset: new Vector3(0.24, -0.16, -0.36),
    viewModelRotation: new Euler(0.035, -0.085, 0.05),
    viewModelScale: 0.245,
    pickupScale: 0.375,
    pickupCollider: new Vector3(0.76, 0.4, 0.52),
  },
  iceGun: {
    id: "iceGun",
    displayName: "Ice Gun",
    modelId: "gravityGun",
    pickupModelId: "gravityGun",
    category: "special",
    type: "iceGun",
    handedness: "twoHanded",
    damage: 0,
    fireRate: 18,
    magazineSize: 0,
    reserveAmmoMax: 0,
    ammoPerPickup: 0,
    spread: 0,
    range: 18,
    impulse: 0,
    reloadTime: 0,
    recoil: { vertical: 0.025, horizontal: 0.012, recovery: 11 },
    fireMode: "auto",
    reloadAnimationPitch: 0.35,
    muzzleFlash: {
      color: 0x8fe6ff,
      intensity: 0.95,
      duration: 0.08,
      size: 0.16,
    },
    canReceiveAmmoFromDuplicatePickup: false,
    hasAmmo: false,
    viewModelOffset: new Vector3(0.235, -0.155, -0.355),
    viewModelRotation: new Euler(0.03, -0.09, 0.048),
    viewModelScale: 0.245,
    pickupScale: 0.375,
    pickupCollider: new Vector3(0.76, 0.4, 0.52),
    noise: {
      fireRadius: 8,
      fireKind: "movement",
    },
  },
  portalGun: {
    id: "portalGun",
    displayName: "Portal Gun",
    modelId: "portalGun",
    pickupModelId: "portalGun",
    category: "special",
    type: "portalGun",
    handedness: "twoHanded",
    damage: 0,
    fireRate: 2,
    magazineSize: 0,
    reserveAmmoMax: 0,
    ammoPerPickup: 0,
    spread: 0,
    range: 60,
    impulse: 0,
    reloadTime: 0,
    recoil: { vertical: 0.02, horizontal: 0.008, recovery: 10 },
    fireMode: "semi",
    reloadAnimationPitch: 0.35,
    muzzleFlash: {
      color: 0x3fa7ff,
      intensity: 0.9,
      duration: 0.08,
      size: 0.15,
    },
    canReceiveAmmoFromDuplicatePickup: false,
    hasAmmo: false,
    viewModelOffset: new Vector3(0.24, -0.16, -0.36),
    viewModelRotation: new Euler(0.035, -0.085, 0.05),
    viewModelScale: 0.245,
    pickupScale: 0.375,
    pickupCollider: new Vector3(0.76, 0.4, 0.52),
    noise: {
      fireRadius: 6,
      fireKind: "movement",
    },
  },
};

/**
 * Orden canÃ³nico de las armas. Define el orden de cycling dentro de un slot
 * y es el orden de declaraciÃ³n del `WeaponDefinitions`. Cambiar el orden acÃ¡
 * cambia cÃ³mo cicla cada slot.
 */
export const WEAPON_ORDER: readonly WeaponId[] = Object.keys(
  WeaponDefinitions,
) as WeaponId[];

export function getWeaponDefinition(id: WeaponId): WeaponDefinition {
  return WeaponDefinitions[id];
}

export function getAllWeaponDefinitions(): WeaponDefinition[] {
  return WEAPON_ORDER.map((id) => WeaponDefinitions[id]);
}

export function getSlotForCategory(category: WeaponCategory): number {
  return SlotByCategory[category];
}

export function getSlotForWeapon(id: WeaponId): number {
  return SlotByCategory[WeaponDefinitions[id].category];
}

/** LÃ­mites globales del sistema de efectos de armas. */
export const WeaponEffectsConfig = {
  /** MÃ¡ximo de tracers (lÃ­neas de disparo) en escena simultÃ¡neos. */
  maxTracers: 48,
  /** MÃ¡ximo de decals (marcas de impacto) en escena simultÃ¡neos. */
  maxDecals: 48,
  /** DuraciÃ³n (s) del tracer antes de desvanecerse. */
  tracerDuration: 0.06,
  /** DuraciÃ³n (s) del decal antes de desvanecerse. */
  decalDuration: 16,
} as const;
