import { buildHouse, type HouseSpec } from '@game/levels/builders/HouseBuilder';
import type { LevelDefinition } from '@game/levels/LevelDefinition';

const HOUSES: HouseSpec[] = [
  {
    id: 'cabin',
    center: [18, -12],
    floorY: 2.5,
    width: 5,
    depth: 5,
    height: 3,
    door: { side: 'south', width: 1.2 },
  },
  {
    id: 'house',
    center: [-20, 15],
    floorY: -1,
    width: 7,
    depth: 6,
    height: 3.2,
    door: { side: 'south', width: 1.4 },
  },
  {
    id: 'shed',
    center: [25, 20],
    floorY: 1,
    width: 8,
    depth: 4,
    height: 3,
    removeWall: 'west',
  },
  {
    id: 'tower',
    center: [-25, -20],
    floorY: 0.5,
    width: 4,
    depth: 4,
    height: 5,
    door: { side: 'east', width: 1.2 },
  },
];

export const SnowFieldLevel: LevelDefinition = {
  id: 'snow-field',
  title: 'Campo Nevado',
  description: 'Exterior abierto con colinas suaves y 4 estructuras esparcidas. Demo del sistema de terreno.',
  background: 0xb6c7d6,
  sun: {
    direction: [0.4, 1.0, 0.3],
    color: 0xe8edf2,
    intensity: 1.8,
  },
  playerStart: [0, 10, 0],
  audio: {
    ambiences: ['background.wind', 'background.hl2.wind.wasteland'],
    soundscape: 'wasteland',
    footstepSounds: [
      'footsteps.snow1',
      'footsteps.snow2',
      'footsteps.snow3',
      'footsteps.snow4',
    ],
  },
  terrain: {
    id: 'snow-terrain',
    position: [0, 0, 0],
    size: [120, 120],
    widthSamples: 97,
    depthSamples: 97,
    source: {
      kind: 'noise',
      seed: 42,
      octaves: 4,
      frequency: 0.025,
      persistence: 0.5,
      lacunarity: 2.1,
      amplitude: 3.5,
      baseHeight: 0,
      flattenRegions: [
        { center: [0, 0], radius: 6, falloff: 4, height: 0 },
        { center: [18, -12], radius: 5, falloff: 3, height: 2.5 },
        { center: [-20, 15], radius: 5, falloff: 3, height: -1 },
        { center: [25, 20], radius: 6, falloff: 4, height: 1 },
        { center: [-25, -20], radius: 4, falloff: 3, height: 0.5 },
      ],
    },
    material: 'snow',
  },
  staticBoxes: [],
  buildings: HOUSES.map(buildHouse),
  dynamicBoxes: [
    { id: 'crate-sf-01', position: [18, 5, -8], size: [0.9, 0.9, 0.9], mass: 1.4, material: 'crate' },
    { id: 'crate-sf-02', position: [17, 5, -7], size: [0.7, 0.7, 0.7], mass: 0.8, material: 'crate' },
    { id: 'crate-sf-03', position: [10, 5, 0], size: [1.1, 1.1, 1.1], mass: 2.0, material: 'crate' },
    { id: 'barrel-sf-04', position: [18, 5, 18], size: [0.8, 1.2, 0.8], mass: 1.2, material: 'hazard' },
    { id: 'barrel-sf-05', position: [19, 5, 20], size: [0.8, 1.2, 0.8], mass: 1.2, material: 'hazard' },
    { id: 'crate-sf-06', position: [-22, 4, -16], size: [1.0, 1.0, 1.0], mass: 1.5, material: 'crate' },
    { id: 'crate-sf-07', position: [-10, 4, 8], size: [1.2, 1.2, 1.2], mass: 2.5, material: 'crate' },
    { id: 'crate-sf-08', position: [-12, 4, 6], size: [0.6, 0.6, 0.6], mass: 0.5, material: 'dynamic' },
  ],
  doors: [],
  npcs: [
    { id: 'gunship-sf-01', position: [0, 22, -34], characterId: 'gunship' },
    { id: 'zombie-sf-01', position: [14, 5, -8], characterId: 'zombie' },
    { id: 'alyx-sf-01', position: [3, 6, 4], characterId: 'alyx' },
    { id: 'combine-sf-01', position: [-18, 5, 14], characterId: 'combine' },
    { id: 'combine-sf-02', position: [-22, 5, 18], characterId: 'combine' },
    { id: 'combine-sf-03', position: [22, 5, 18], characterId: 'combine' },
  ],
  weaponPickups: [
    { id: 'pickup-pistol-sf', weaponId: 'pistol', position: [-5, 6, -2] },
    { id: 'pickup-smg-sf', weaponId: 'smg', position: [-3, 6, -2] },
    { id: 'pickup-ar3-sf', weaponId: 'ar3', position: [-1, 6, -2] },
    { id: 'pickup-crowbar-sf', weaponId: 'crowbar', position: [1, 6, -2] },
    { id: 'pickup-gravity-gun-sf', weaponId: 'gravityGun', position: [3, 6, -2] },
    { id: 'pickup-shotgun-sf', weaponId: 'shotgun', position: [5, 6, -2] },
    { id: 'pickup-rpg-sf', weaponId: 'rpg', position: [7, 6, -2] },
    { id: 'pickup-grenade-sf-1', weaponId: 'grenade', position: [8.5, 6, -2] },
    { id: 'pickup-grenade-sf-2', weaponId: 'grenade', position: [9, 6, -2] },
    { id: 'pickup-grenade-sf-3', weaponId: 'grenade', position: [9.5, 6, -2] },
  ],
  ammoPickups: [
    { id: 'ammo-pistol-sf', ammoId: 'pistol', position: [-5, 6, -3.4] },
    { id: 'ammo-smg-sf', ammoId: 'smg', position: [-3, 6, -3.4] },
    { id: 'ammo-ar3-sf', ammoId: 'ar3', position: [-1, 6, -3.4] },
    { id: 'ammo-shotgun-sf', ammoId: 'shotgun', position: [5, 6, -3.4] },
    { id: 'ammo-rpg-sf', ammoId: 'rpg', position: [7, 6, -3.4] },
    { id: 'ammo-grenade-sf', ammoId: 'grenade', position: [8.5, 6, -3.4] },
  ],
  triggers: [],
};
