import { Vector3 } from "three";
import type { ModelAssetId } from "@engine/assets/AssetManifest";
import type {
  CharacterAIProfileId,
  CharacterDefinition,
  CharacterId,
} from "@engine/characters/CharacterDefinition";
import { BlobConfig } from "@game/config/blob.config";

const BLOB_AGGREGATE_RADIUS = BlobConfig.armor.aggregateRadius;

const baseHumanoid = {
  type: "humanoid",
  faction: "zombies",
  aiProfileId: "zombieMelee",
  height: 1.75,
  radius: 0.35,
  mass: 60,
  visualScale: 1,
  visualRotationY: 0,
  visualOffset: new Vector3(0, -0.875, 0),
  movement: {
    maxSpeed: 2.2,
    acceleration: 10,
    turnSpeed: 6,
    rotationSmoothing: 0.15,
    faceTargetDeadzone: 0.08,
    turnBeforeMoveAngle: 0.65,
    minMoveFacingDot: 0.35,
    gravity: 28,
    linearDamping: 4,
    angularDamping: 8,
  },
  health: {
    maxHealth: 100,
  },
  animation: {
    mode: "procedural",
    ignoreBakedAnimations: true,
    restPose: {
      type: "tpose_to_relaxed",
      leftUpperArm: { z: 1.05 },
      rightUpperArm: { z: -1.05 },
      leftForearm: { z: 0.2 },
      rightForearm: { z: -0.2 },
      spine: { x: 0.03 },
      chest: { x: 0.02 },
      head: { x: -0.02 },
    },
    armsMode: "relaxed",
    boneAxes: {
      legSwingAxis: "x",
      armSwingAxis: "x",
      kneeBendAxis: "x",
      elbowBendAxis: "x",
      spineLeanAxis: "x",
      headYawAxis: "y",
    },
    walkStyle: "normal",
    useLookAt: true,
    useStumble: true,
    walk: {},
    maxHeadYaw: 0.65,
    maxHeadPitch: 0.35,
  },
  ragdoll: {
    enabled: true,
    mode: "passiveOnDeath",
    activeWhileAlive: true,
    passiveOnDeath: true,
    bodyPartCollisions: true,
    impulseScale: 45,
    maxDeathLinearVelocity: 8,
    maxDeathAngularVelocity: 12,
    maxPartLinearVelocity: 10,
    maxPartAngularVelocity: 25,
    linearDamping: 0.1,
    angularDamping: 0.9,
    friction: 0.9,
    colliderScale: 1,
    enableJoints: true,
    corpseCleanupDelay: 0,
    debug: false,
  },
  collider: {
    height: 1.75,
    radius: 0.35,
    mass: 60,
    stepOffset: 0.4,
    snapToGround: 0.45,
  },
  ai: {
    detectionRange: 24,
  },
  perception: {
    viewDistance: 22,
    viewConeRadians: Math.PI * 0.75,
    hearingRadius: 14,
    memoryDuration: 6,
    // Offset desde el CENTRO de la capsula (convencion de PerceptionSystem).
    eyeHeight: 0.62,
  },
  attack: {
    enabled: false,
    type: "melee",
    damage: 8,
    range: 1.4,
    cooldown: 1.2,
    windup: 0.35,
    hitWindow: 0.2,
    knockback: 1.6,
    requireLineOfSight: false,
    facingDotThreshold: 0.35,
  },
  stumble: {
    stumbleImpulseThreshold: 0.2,
    stumbleDuration: 0.75,
    fallAngleThreshold: 0.78,
    getUpDelay: 0.75,
    recoverDuration: 0.65,
  },
  debug: false,
} satisfies Omit<CharacterDefinition, "id" | "modelId">;

/**
 * Rebelde de la resistencia (citizen HL2): base de las 6 variantes visuales
 * y el medic. Aliados del player, SMG con punteria peor que Alyx, siguen al
 * jugador y respetan slots de ataque (ver `rebelPreset`).
 */
function buildRebelDefinition(
  id: CharacterId,
  modelId: ModelAssetId,
  overrides: { aiProfileId?: CharacterAIProfileId } = {},
): CharacterDefinition {
  return {
    ...baseHumanoid,
    id,
    modelId,
    faction: "resistance",
    aiProfileId: overrides.aiProfileId ?? "rebelAlly",
    visualOffset: new Vector3(0, -0.875, 0),
    movement: {
      ...baseHumanoid.movement,
      maxSpeed: 4.0,
      acceleration: 15,
      turnSpeed: 9,
      rotationSmoothing: 0.22,
      turnBeforeMoveAngle: 1.0,
      minMoveFacingDot: 0.2,
    },
    health: { maxHealth: 60 },
    flinch: { duration: 0.18, cooldown: 1.2 },
    animation: {
      ...baseHumanoid.animation,
      restPose: {
        type: "tpose_to_relaxed",
        leftUpperArm: { z: 1.05, x: -0.3 },
        rightUpperArm: { z: -1.05, x: -0.3 },
        leftForearm: { z: 0.2, x: -0.5 },
        rightForearm: { z: -0.2, x: -0.5 },
        spine: { x: 0.02 },
        chest: { x: 0.01 },
        head: { x: -0.02 },
      },
      armsMode: "weaponAim",
      walkStyle: "normal",
      walk: {
        stepFrequency: 5.2,
        strideLength: 0.52,
        stepHeight: 0.04,
        armSwing: 0.13,
        torsoBob: 0.024,
        torsoLean: 0.07,
        maxLegSwing: 0.5,
        maxKneeBend: 0.3,
        maxArmSwing: 0.19,
      },
    },
    perception: {
      viewDistance: 26,
      viewConeRadians: Math.PI * (130 / 180),
      hearingRadius: 16,
      memoryDuration: 5,
      eyeHeight: 0.62,
      detection: {
        baseTime: 0.9,
        instantRange: 8,
        suspicionThreshold: 0.35,
        decayRate: 0.6,
        alertMultiplier: 3,
      },
    },
    ai: { detectionRange: 26 },
    attack: {
      enabled: true,
      type: "ranged",
      damage: 0,
      range: 18,
      cooldown: 0.9,
      windup: 0,
      hitWindow: 0,
      knockback: 0,
      requireLineOfSight: true,
      facingDotThreshold: 0.5,
      ranged: {
        weaponId: "smg",
        burstSize: 5,
        pauseBetweenBursts: 1.0,
        aimError: 0.1,
        aimErrorSettled: 0.035,
        aimSettleDuration: 1.4,
        aimTime: 0.25,
        reactionTime: 0.3,
      },
    },
    stumble: {
      stumbleImpulseThreshold: 0.35,
      stumbleDuration: 0.4,
      fallAngleThreshold: 0.95,
      getUpDelay: 0.8,
      recoverDuration: 0.55,
    },
  };
}

export const CharacterPresets: Record<CharacterId, CharacterDefinition> = {
  zombie: {
    ...baseHumanoid,
    id: "zombie",
    modelId: "zombie",
    visualOffset: new Vector3(0, -0.875, 0),
    movement: {
      ...baseHumanoid.movement,
      maxSpeed: 2.05,
      acceleration: 8,
      turnSpeed: 5,
      rotationSmoothing: 0.12,
      turnBeforeMoveAngle: 0.65,
      minMoveFacingDot: 0.35,
    },
    animation: {
      ...baseHumanoid.animation,
      restPose: {
        type: "zombie",
        leftUpperArm: { z: 1.18, x: -0.18 },
        rightUpperArm: { z: -1.18, x: -0.18 },
        leftForearm: { z: 0.32, x: -0.42 },
        rightForearm: { z: -0.32, x: -0.42 },
        spine: { x: 0.08 },
        chest: { x: 0.06 },
        head: { x: -0.05 },
      },
      armsMode: "zombieForward",
      boneAxes: {
        legSwingAxis: "x",
        armSwingAxis: "x",
        kneeBendAxis: "x",
        elbowBendAxis: "x",
        spineLeanAxis: "x",
        headYawAxis: "y",
      },
      walkStyle: "staggered",
      walk: {
        stepFrequency: 3,
        strideLength: 0.45,
        stepHeight: 0.025,
        armSwing: 0.18,
        torsoBob: 0.04,
        torsoLean: 0.12,
        maxLegSwing: 0.55,
        maxKneeBend: 0.28,
        maxFootRotation: 0.04,
        maxSideSwing: 0.015,
        maxArmSwing: 0.22,
        maxTorsoLean: 0.18,
        sideToSide: 0.004,
        randomness: 0.025,
      },
    },
    ragdoll: {
      ...baseHumanoid.ragdoll,
    },
    health: { maxHealth: 50 },
    // Depredador de oido: vision corta y angosta, oreja larga (ver zombiePreset).
    perception: {
      viewDistance: 14,
      viewConeRadians: Math.PI * (100 / 180),
      hearingRadius: 25,
      memoryDuration: 10,
      eyeHeight: 0.62,
    },
    ai: {
      ...baseHumanoid.ai,
      detectionRange: 26,
    },
    attack: {
      enabled: true,
      type: "melee",
      damage: 12,
      range: 1.6,
      cooldown: 1.1,
      windup: 0.35,
      hitWindow: 0.25,
      knockback: 2.0,
      requireLineOfSight: true,
      facingDotThreshold: 0.35,
    },
  },
  combine: {
    ...baseHumanoid,
    id: "combine",
    modelId: "combine",
    faction: "combine",
    aiProfileId: "combineSoldier",
    visualOffset: new Vector3(0, -0.875, 0),
    movement: {
      ...baseHumanoid.movement,
      maxSpeed: 3.8,
      acceleration: 14,
      turnSpeed: 9,
      rotationSmoothing: 0.22,
      turnBeforeMoveAngle: 0.95,
      minMoveFacingDot: 0.2,
    },
    health: { maxHealth: 50 },
    animation: {
      ...baseHumanoid.animation,
      restPose: {
        type: "tpose_to_relaxed",
        leftUpperArm: { z: 1.05, x: -0.35 },
        rightUpperArm: { z: -1.05, x: -0.35 },
        leftForearm: { z: 0.2, x: -0.55 },
        rightForearm: { z: -0.2, x: -0.55 },
        spine: { x: 0.02 },
        chest: { x: 0.01 },
        head: { x: -0.02 },
      },
      armsMode: "weaponAim",
      walkStyle: "normal",
      walk: {
        stepFrequency: 5,
        strideLength: 0.55,
        stepHeight: 0.045,
        armSwing: 0.12,
        torsoBob: 0.025,
        torsoLean: 0.08,
        maxLegSwing: 0.5,
        maxKneeBend: 0.32,
        maxArmSwing: 0.18,
      },
    },
    perception: {
      viewDistance: 32,
      viewConeRadians: Math.PI * (160 / 180),
      hearingRadius: 18,
      memoryDuration: 8,
      eyeHeight: 0.62,
      detection: {
        baseTime: 1.1,
        instantRange: 7,
        suspicionThreshold: 0.35,
        decayRate: 0.6,
        alertMultiplier: 3,
      },
    },
    ai: {
      detectionRange: 32,
    },
    attack: {
      enabled: true,
      type: "ranged",
      damage: 0,
      range: 22,
      cooldown: 0.9,
      windup: 0,
      hitWindow: 0,
      knockback: 0,
      requireLineOfSight: true,
      facingDotThreshold: 0.5,
      ranged: {
        weaponId: "ar3",
        burstSize: 4,
        pauseBetweenBursts: 1.1,
        aimError: 0.16,
        aimErrorSettled: 0.045,
        aimSettleDuration: 1.6,
        aimTime: 0.25,
        reactionTime: 0.35,
      },
      grenade: {
        enabled: true,
        cooldown: 12,
        minRange: 8,
        maxRange: 24,
        damage: 65,
        radius: 4.5,
        impulse: 8,
        fuseSeconds: 3.4,
        launchSpeed: 13,
        launchLift: 5,
        flushAfterMemoryAge: 1.6,
      },
    },
    stumble: {
      stumbleImpulseThreshold: 0.35,
      stumbleDuration: 0.45,
      fallAngleThreshold: 0.9,
      getUpDelay: 0.9,
      recoverDuration: 0.6,
    },
  },
  combineElite: {
    ...baseHumanoid,
    id: "combineElite",
    modelId: "combineElite",
    faction: "combine",
    aiProfileId: "combineSoldier",
    visualOffset: new Vector3(0, -0.875, 0),
    movement: {
      ...baseHumanoid.movement,
      maxSpeed: 3.8,
      acceleration: 14,
      turnSpeed: 9,
      rotationSmoothing: 0.22,
      turnBeforeMoveAngle: 0.95,
      minMoveFacingDot: 0.2,
    },
    // Elite: el doble de aguante, mejor punteria y casi no flinchea.
    health: { maxHealth: 100 },
    flinch: { duration: 0.12, cooldown: 2.5 },
    animation: {
      ...baseHumanoid.animation,
      restPose: {
        type: "tpose_to_relaxed",
        leftUpperArm: { z: 1.05, x: -0.35 },
        rightUpperArm: { z: -1.05, x: -0.35 },
        leftForearm: { z: 0.2, x: -0.55 },
        rightForearm: { z: -0.2, x: -0.55 },
        spine: { x: 0.02 },
        chest: { x: 0.01 },
        head: { x: -0.02 },
      },
      armsMode: "weaponAim",
      walkStyle: "normal",
      walk: {
        stepFrequency: 5,
        strideLength: 0.55,
        stepHeight: 0.045,
        armSwing: 0.12,
        torsoBob: 0.025,
        torsoLean: 0.08,
        maxLegSwing: 0.5,
        maxKneeBend: 0.32,
        maxArmSwing: 0.18,
      },
    },
    perception: {
      viewDistance: 32,
      viewConeRadians: Math.PI * (160 / 180),
      hearingRadius: 18,
      memoryDuration: 8,
      eyeHeight: 0.62,
      detection: {
        baseTime: 1.1,
        instantRange: 7,
        suspicionThreshold: 0.35,
        decayRate: 0.6,
        alertMultiplier: 3,
      },
    },
    ai: {
      detectionRange: 32,
    },
    attack: {
      enabled: true,
      type: "ranged",
      damage: 0,
      range: 22,
      cooldown: 0.9,
      windup: 0,
      hitWindow: 0,
      knockback: 0,
      requireLineOfSight: true,
      facingDotThreshold: 0.5,
      ranged: {
        weaponId: "ar3",
        burstSize: 4,
        pauseBetweenBursts: 1.1,
        aimError: 0.1,
        aimErrorSettled: 0.03,
        aimSettleDuration: 1.6,
        aimTime: 0.25,
        reactionTime: 0.35,
      },
      grenade: {
        enabled: true,
        cooldown: 12,
        minRange: 8,
        maxRange: 24,
        damage: 65,
        radius: 4.5,
        impulse: 8,
        fuseSeconds: 3.4,
        launchSpeed: 13,
        launchLift: 5,
        flushAfterMemoryAge: 1.6,
      },
    },
    stumble: {
      stumbleImpulseThreshold: 0.35,
      stumbleDuration: 0.45,
      fallAngleThreshold: 0.9,
      getUpDelay: 0.9,
      recoverDuration: 0.6,
    },
  },
  combineShotgunner: {
    ...baseHumanoid,
    id: "combineShotgunner",
    modelId: "combineShotgunner",
    faction: "combine",
    aiProfileId: "combineSoldier",
    visualOffset: new Vector3(0, -0.875, 0),
    movement: {
      ...baseHumanoid.movement,
      maxSpeed: 3.8,
      acceleration: 14,
      turnSpeed: 9,
      rotationSmoothing: 0.22,
      turnBeforeMoveAngle: 0.95,
      minMoveFacingDot: 0.2,
    },
    health: { maxHealth: 50 },
    animation: {
      ...baseHumanoid.animation,
      restPose: {
        type: "tpose_to_relaxed",
        leftUpperArm: { z: 1.05, x: -0.35 },
        rightUpperArm: { z: -1.05, x: -0.35 },
        leftForearm: { z: 0.2, x: -0.55 },
        rightForearm: { z: -0.2, x: -0.55 },
        spine: { x: 0.02 },
        chest: { x: 0.01 },
        head: { x: -0.02 },
      },
      armsMode: "weaponAim",
      walkStyle: "normal",
      walk: {
        stepFrequency: 5,
        strideLength: 0.55,
        stepHeight: 0.045,
        armSwing: 0.12,
        torsoBob: 0.025,
        torsoLean: 0.08,
        maxLegSwing: 0.5,
        maxKneeBend: 0.32,
        maxArmSwing: 0.18,
      },
    },
    perception: {
      viewDistance: 32,
      viewConeRadians: Math.PI * (160 / 180),
      hearingRadius: 18,
      memoryDuration: 8,
      eyeHeight: 0.62,
      detection: {
        baseTime: 1.1,
        instantRange: 7,
        suspicionThreshold: 0.35,
        decayRate: 0.6,
        alertMultiplier: 3,
      },
    },
    ai: {
      detectionRange: 32,
    },
    attack: {
      enabled: true,
      type: "ranged",
      damage: 0,
      range: 14,
      cooldown: 0.9,
      windup: 0,
      hitWindow: 0,
      knockback: 0,
      requireLineOfSight: true,
      facingDotThreshold: 0.5,
      ranged: {
        weaponId: "shotgun",
        burstSize: 2,
        pauseBetweenBursts: 1.5,
        aimError: 0.16,
        aimErrorSettled: 0.06,
        aimSettleDuration: 1.6,
        aimTime: 0.25,
        reactionTime: 0.35,
      },
      grenade: {
        enabled: true,
        cooldown: 12,
        minRange: 8,
        maxRange: 24,
        damage: 65,
        radius: 4.5,
        impulse: 8,
        fuseSeconds: 3.4,
        launchSpeed: 13,
        launchLift: 5,
        flushAfterMemoryAge: 1.6,
      },
    },
    stumble: {
      stumbleImpulseThreshold: 0.35,
      stumbleDuration: 0.45,
      fallAngleThreshold: 0.9,
      getUpDelay: 0.9,
      recoverDuration: 0.6,
    },
  },
  alyx: {
    ...baseHumanoid,
    id: "alyx",
    modelId: "alyx",
    faction: "resistance",
    aiProfileId: "alyxSupport",
    visualOffset: new Vector3(0, -0.875, 0),
    movement: {
      ...baseHumanoid.movement,
      maxSpeed: 4.2,
      acceleration: 16,
      turnSpeed: 10,
      rotationSmoothing: 0.22,
      turnBeforeMoveAngle: 1.0,
      minMoveFacingDot: 0.2,
    },
    health: { maxHealth: 120 },
    animation: {
      ...baseHumanoid.animation,
      restPose: {
        type: "tpose_to_relaxed",
        leftUpperArm: { z: 1.05, x: -0.3 },
        rightUpperArm: { z: -1.05, x: -0.3 },
        leftForearm: { z: 0.2, x: -0.5 },
        rightForearm: { z: -0.2, x: -0.5 },
        spine: { x: 0.02 },
        chest: { x: 0.01 },
        head: { x: -0.02 },
      },
      armsMode: "weaponAim",
      walkStyle: "normal",
      walk: {
        stepFrequency: 5.5,
        strideLength: 0.5,
        stepHeight: 0.04,
        armSwing: 0.14,
        torsoBob: 0.022,
        torsoLean: 0.07,
        maxLegSwing: 0.5,
        maxKneeBend: 0.28,
        maxArmSwing: 0.2,
      },
    },
    perception: {
      viewDistance: 28,
      viewConeRadians: Math.PI * (130 / 180),
      hearingRadius: 16,
      memoryDuration: 5,
      eyeHeight: 0.62,
      detection: {
        baseTime: 0.9,
        instantRange: 8,
        suspicionThreshold: 0.35,
        decayRate: 0.6,
        alertMultiplier: 3,
      },
    },
    ai: {
      detectionRange: 28,
    },
    attack: {
      enabled: true,
      type: "ranged",
      damage: 0,
      range: 20,
      cooldown: 0.7,
      windup: 0,
      hitWindow: 0,
      knockback: 0,
      requireLineOfSight: true,
      facingDotThreshold: 0.5,
      ranged: {
        weaponId: "pistol",
        burstSize: 2,
        pauseBetweenBursts: 0.8,
        aimError: 0.035,
        aimErrorSettled: 0.008,
        aimSettleDuration: 1.2,
        aimTime: 0.2,
        reactionTime: 0.25,
      },
    },
    stumble: {
      stumbleImpulseThreshold: 0.35,
      stumbleDuration: 0.4,
      fallAngleThreshold: 0.95,
      getUpDelay: 0.8,
      recoverDuration: 0.55,
    },
  },
  rebelF1: buildRebelDefinition("rebelF1", "rebelF1"),
  rebelF2: buildRebelDefinition("rebelF2", "rebelF2"),
  rebelF3: buildRebelDefinition("rebelF3", "rebelF3"),
  rebelM1: buildRebelDefinition("rebelM1", "rebelM1"),
  rebelM2: buildRebelDefinition("rebelM2", "rebelM2"),
  rebelM3: buildRebelDefinition("rebelM3", "rebelM3"),
  rebelMedic: buildRebelDefinition("rebelMedic", "rebelF2", { aiProfileId: "rebelMedic" }),
  headcrab: {
    ...baseHumanoid,
    id: "headcrab",
    modelId: "headcrab",
    type: "creature",
    faction: "zombies",
    aiProfileId: "headcrabMelee",
    height: 0.6,
    radius: 0.3,
    mass: 8,
    // El GLB del headcrab esta autorizado ~100x mas chico que metros: sin esto
    // renderiza ~3mm (invisible). Ver §medicion runtime del skinned bbox.
    visualScale: 130,
    visualOffset: new Vector3(0, -0.3, 0),
    health: { maxHealth: 30 },
    collider: {
      height: 0.6,
      radius: 0.3,
      mass: 8,
      stepOffset: 0.4,
      snapToGround: 0.45,
    },
    perception: {
      viewDistance: 16,
      viewConeRadians: Math.PI * (120 / 180),
      hearingRadius: 20,
      memoryDuration: 6,
      eyeHeight: 0.4,
    },
    ai: { detectionRange: 18 },
    // Mordisco de contacto: `windup: 0` + `hitWindow` largo => al abrir la
    // ventana en el lanzamiento del salto, el daño conecta apenas el cuerpo
    // entra en `range` durante el vuelo (ver `createLeapTask`). El `cooldown`
    // evita multi-mordisco por salto y marca la cadencia point-blank.
    attack: {
      enabled: true,
      type: "melee",
      damage: 12,
      range: 1.3,
      cooldown: 1.4,
      windup: 0,
      hitWindow: 1.0,
      knockback: 1.5,
      requireLineOfSight: false,
      facingDotThreshold: 0.2,
    },
  },
  manhack: {
    ...baseHumanoid,
    id: "manhack",
    modelId: undefined,
    type: "robot",
    faction: "combine",
    aiProfileId: "manhackFlyer",
    height: 0.4,
    radius: 0.3,
    mass: 5,
    visualScale: 1.2,
    visualOffset: new Vector3(0, 0, 0),
    movement: {
      ...baseHumanoid.movement,
      gravity: 0,
    },
    health: { maxHealth: 25 },
    collider: {
      height: 0.4,
      radius: 0.3,
      mass: 5,
      stepOffset: 0,
      snapToGround: 0,
    },
    perception: {
      viewDistance: 24,
      viewConeRadians: Math.PI * (150 / 180),
      hearingRadius: 16,
      memoryDuration: 6,
      eyeHeight: 0.45,
    },
    ai: { detectionRange: 24 },
    attack: {
      enabled: true,
      type: "melee",
      // `damage` = daño por cuchillazo de contacto (slice del motor), ×2 vs player.
      damage: 4,
      range: 1.6,
      cooldown: 0.6,
      windup: 0.1,
      hitWindow: 0.15,
      knockback: 0.5,
      requireLineOfSight: false,
      facingDotThreshold: 0.2,
    },
  },
  gunship: {
    ...baseHumanoid,
    id: "gunship",
    modelId: undefined,
    type: "robot",
    faction: "combine",
    aiProfileId: "gunshipBoss",
    height: 2.4,
    radius: 0.95,
    mass: 900,
    visualScale: 2.2,
    visualOffset: new Vector3(0, 0, 0),
    movement: {
      ...baseHumanoid.movement,
      maxSpeed: 8,
      acceleration: 3.8,
      turnSpeed: 2.8,
      gravity: 0,
      linearDamping: 1.2,
      angularDamping: 2.4,
    },
    health: { maxHealth: 600 },
    collider: {
      height: 2.4,
      radius: 0.95,
      mass: 900,
      stepOffset: 0,
      snapToGround: 0,
    },
    perception: {
      viewDistance: 55,
      viewConeRadians: Math.PI,
      hearingRadius: 28,
      memoryDuration: 7,
      // El origen de LOS queda sobre la capsula: evita self-hit del raycast.
      eyeHeight: 1.35,
    },
    ai: { detectionRange: 55 },
    attack: {
      enabled: true,
      type: "ranged",
      damage: 6,
      range: 60,
      cooldown: 1.6,
      windup: 0.45,
      hitWindow: 0,
      knockback: 0,
      requireLineOfSight: true,
      facingDotThreshold: 0.25,
    },
    ragdoll: {
      ...baseHumanoid.ragdoll,
      enabled: false,
    },
  },
  strider: {
    ...baseHumanoid,
    id: "strider",
    modelId: undefined,
    type: "robot",
    faction: "combine",
    aiProfileId: "striderBoss",
    height: 9.5,
    radius: 1.35,
    mass: 3200,
    visualScale: 1,
    visualOffset: new Vector3(0, 0, 0),
    movement: {
      ...baseHumanoid.movement,
      maxSpeed: 4.6,
      acceleration: 3.2,
      turnSpeed: 1.45,
      gravity: 20.5,
      linearDamping: 1.8,
      angularDamping: 3,
    },
    health: { maxHealth: 1500 },
    collider: {
      height: 9.5,
      radius: 1.35,
      mass: 3200,
      stepOffset: 0,
      snapToGround: 0,
    },
    perception: {
      viewDistance: 85,
      viewConeRadians: Math.PI,
      hearingRadius: 38,
      memoryDuration: 8,
      // Ojo a la altura de la cabeza (ver striderPreset). El runtime usa la
      // percepcion del preset; esto queda en sync para evitar confusion.
      eyeHeight: 0.4,
    },
    ai: { detectionRange: 85 },
    attack: {
      enabled: true,
      type: "ranged",
      damage: 6,
      range: 85,
      cooldown: 1.1,
      windup: 0.35,
      hitWindow: 0,
      knockback: 0,
      requireLineOfSight: true,
      facingDotThreshold: 0.2,
    },
    ragdoll: {
      ...baseHumanoid.ragdoll,
      enabled: false,
    },
  },
  blob: {
    ...baseHumanoid,
    id: "blob",
    modelId: undefined,
    type: "creature",
    faction: "blob",
    aiProfileId: "blobArmor",
    // Dimensiones agregadas (core + órbita + esfera máxima) para spawn y
    // separación de IA. El collider físico real del core usa BlobConfig.core.
    height: BLOB_AGGREGATE_RADIUS * 2,
    radius: BLOB_AGGREGATE_RADIUS,
    mass: BlobConfig.core.mass,
    visualScale: 1,
    visualOffset: new Vector3(0, 0, 0),
    movement: {
      ...baseHumanoid.movement,
      maxSpeed: BlobConfig.predator.moveSpeed,
      acceleration: BlobConfig.predator.movementAcceleration,
      turnSpeed: 2,
      rotationSmoothing: 0,
      faceTargetDeadzone: 0,
      turnBeforeMoveAngle: Math.PI,
      minMoveFacingDot: 1,
      linearDamping: BlobConfig.armor.linearDamping,
      angularDamping: BlobConfig.armor.angularDamping,
    },
    health: { maxHealth: BlobConfig.core.maxHealth },
    animation: {
      ...baseHumanoid.animation,
      restPose: { type: "none" },
      armsMode: "relaxed",
      useLookAt: false,
      useStumble: false,
      walk: {},
    },
    ragdoll: {
      ...baseHumanoid.ragdoll,
      enabled: false,
    },
    collider: {
      height: BLOB_AGGREGATE_RADIUS * 2,
      radius: BLOB_AGGREGATE_RADIUS,
      mass: BlobConfig.core.mass,
      stepOffset: 0,
      snapToGround: 0,
    },
    ai: { detectionRange: BlobConfig.predator.detectionRange },
    perception: {
      viewDistance: BlobConfig.predator.detectionRange,
      viewConeRadians: Math.PI,
      hearingRadius: 10,
      memoryDuration: 2,
      eyeHeight: 0,
    },
    attack: {
      ...baseHumanoid.attack,
      enabled: false,
      damage: 0,
      range: 0,
      knockback: 0,
    },
  },
  floorTurret: {
    ...baseHumanoid,
    id: "floorTurret",
    modelId: undefined, // visual procedural: createTurretVisual()
    type: "robot",
    faction: "combine",
    aiProfileId: "floorTurret",
    height: 1.2,
    radius: 0.3,
    mass: 2,
    visualScale: 1,
    visualOffset: new Vector3(0, 0, 0),
    // Salud altísima: las balas casi no la dañan; se neutraliza tumbándola
    // (gravity gun / empujón / explosión). Ver `buildTurretPreset`.
    health: { maxHealth: 100000 },
    collider: {
      height: 1.2,
      radius: 0.3,
      mass: 2,
      stepOffset: 0,
      snapToGround: 0,
    },
    perception: {
      viewDistance: 28,
      viewConeRadians: Math.PI * (75 / 180),
      hearingRadius: 0,
      memoryDuration: 3,
      eyeHeight: 0.7,
    },
    ai: { detectionRange: 28 },
  },
  placeholderHumanoid: {
    ...baseHumanoid,
    id: "placeholderHumanoid",
    modelId: undefined,
  },
};

/**
 * Un personaje volador (gravity 0, ej. manhack) no debe ser pegado al suelo por
 * el `SpawnValidator` al spawnear: conserva la altura de diseño y vuela en el aire.
 */
export function isFlyingCharacter(def: CharacterDefinition): boolean {
  return def.movement.gravity === 0;
}
