import { Vector3 } from "three";
import type { CharacterDefinition, CharacterId } from "./CharacterDefinition";

const baseHumanoid = {
  type: "humanoid",
  height: 1.75,
  radius: 0.35,
  mass: 60,
  visualScale: 1,
  visualRotationY: 0,
  visualOffset: new Vector3(0, -0.875, 0),
  movement: {
    maxSpeed: 2.2,
    acceleration: 10,
    turnSpeed: 6,
    rotationSmoothing: 0.15,
    faceTargetDeadzone: 0.08,
    turnBeforeMoveAngle: 0.65,
    minMoveFacingDot: 0.35,
    gravity: 28,
    linearDamping: 4,
    angularDamping: 8,
  },
  health: {
    maxHealth: 100,
  },
  animation: {
    mode: "procedural",
    ignoreBakedAnimations: true,
    restPose: {
      type: "tpose_to_relaxed",
      leftUpperArm: { z: 1.05 },
      rightUpperArm: { z: -1.05 },
      leftForearm: { z: 0.2 },
      rightForearm: { z: -0.2 },
      spine: { x: 0.03 },
      chest: { x: 0.02 },
      head: { x: -0.02 },
    },
    armsMode: "relaxed",
    boneAxes: {
      legSwingAxis: "x",
      armSwingAxis: "x",
      kneeBendAxis: "x",
      elbowBendAxis: "x",
      spineLeanAxis: "x",
      headYawAxis: "y",
    },
    walkStyle: "normal",
    useLookAt: true,
    useStumble: true,
    walk: {},
    maxHeadYaw: 0.65,
    maxHeadPitch: 0.35,
  },
  ragdoll: {
    enabled: true,
    mode: "passiveOnDeath",
    activeWhileAlive: true,
    passiveOnDeath: true,
    bodyPartCollisions: true,
    preserveOriginalSkinnedMesh: true,
    useDebugMeshes: false,
    impulseScale: 0.35,
    maxDeathLinearVelocity: 3,
    maxDeathAngularVelocity: 4,
    initialDampingDuration: 0.5,
    linearDamping: 2.5,
    angularDamping: 3.5,
    density: 0.75,
    colliderScale: 0.78,
    enableJoints: true,
    jointStrength: 0.8,
    jointDamping: 0.7,
    bodyPartDamping: 2,
    maxPartLinearVelocity: 4,
    maxPartAngularVelocity: 5,
    stiffness: 0.55,
    damping: 0.75,
    balanceStrength: 0.8,
    uprightStrength: 0.9,
    limbFollowStrength: 0.45,
    maxCorrectionForce: 36,
    stumbleThreshold: 0.65,
    fallThreshold: 1.1,
    recoverDelay: 1.2,
    debug: false,
  },
  collider: {
    height: 1.75,
    radius: 0.35,
    mass: 60,
    stepOffset: 0.4,
    snapToGround: 0.45,
  },
  ai: {
    detectionRange: 24,
  },
  attack: {
    enabled: false,
    type: "melee",
    damage: 8,
    range: 1.4,
    cooldown: 1.2,
    windup: 0.35,
    hitWindow: 0.2,
    knockback: 1.6,
    requireLineOfSight: false,
    facingDotThreshold: 0.35,
  },
  stumble: {
    stumbleImpulseThreshold: 0.2,
    stumbleDuration: 0.75,
    fallAngleThreshold: 0.78,
    getUpDelay: 0.75,
    recoverDuration: 0.65,
  },
  debug: false,
} satisfies Omit<CharacterDefinition, "id" | "modelId">;

export const CharacterPresets: Record<CharacterId, CharacterDefinition> = {
  zombie: {
    ...baseHumanoid,
    id: "zombie",
    modelId: "zombie",
    visualOffset: new Vector3(0, -0.875, 0),
    movement: {
      ...baseHumanoid.movement,
      maxSpeed: 2.05,
      acceleration: 8,
      turnSpeed: 5,
      rotationSmoothing: 0.12,
      turnBeforeMoveAngle: 0.65,
      minMoveFacingDot: 0.35,
    },
    animation: {
      ...baseHumanoid.animation,
      restPose: {
        type: "zombie",
        leftUpperArm: { z: 1.18, x: -0.18 },
        rightUpperArm: { z: -1.18, x: -0.18 },
        leftForearm: { z: 0.32, x: -0.42 },
        rightForearm: { z: -0.32, x: -0.42 },
        spine: { x: 0.08 },
        chest: { x: 0.06 },
        head: { x: -0.05 },
      },
      armsMode: "zombieForward",
      boneAxes: {
        legSwingAxis: "x",
        armSwingAxis: "x",
        kneeBendAxis: "x",
        elbowBendAxis: "x",
        spineLeanAxis: "x",
        headYawAxis: "y",
      },
      walkStyle: "staggered",
      walk: {
        stepFrequency: 3,
        strideLength: 0.45,
        stepHeight: 0.025,
        armSwing: 0.18,
        torsoBob: 0.04,
        torsoLean: 0.12,
        maxLegSwing: 0.55,
        maxKneeBend: 0.28,
        maxFootRotation: 0.04,
        maxSideSwing: 0.015,
        maxArmSwing: 0.22,
        maxTorsoLean: 0.18,
        sideToSide: 0.004,
        randomness: 0.025,
      },
    },
    ragdoll: {
      ...baseHumanoid.ragdoll,
      impulseScale: 0.35,
      debug: false,
    },
    ai: {
      ...baseHumanoid.ai,
      detectionRange: 26,
    },
    attack: {
      enabled: true,
      type: "melee",
      damage: 12,
      range: 1.6,
      cooldown: 1.1,
      windup: 0.35,
      hitWindow: 0.25,
      knockback: 2.0,
      requireLineOfSight: false,
      facingDotThreshold: 0.35,
    },
  },
  placeholderHumanoid: {
    ...baseHumanoid,
    id: "placeholderHumanoid",
    modelId: undefined,
  },
};
